# -*- coding: utf-8 -*-
"""A Simple Loan Eligibility APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnAdYZkMFWQwhFH2XPehFIjITllO2vvd
"""

# Welcome Message
print("Hi there! Welcome to SIGMA Bank loan eligibility check app" )
print("Ready to take the next step? Complete a few simple details to see the loan options available to you")


# Customer Information
customer_id = input("Please enter your customer ID: ")
customer_name = input("Please enter your name: ")
customer_age = input("Please enter your age: ")
monthly_income = input("Please enter your monthly income: ")
credit_score = input("Please enter your credit score: ")
number_of_missed_payments = input("Please enter the number of missed payments: ")
country_of_residence = input("Please enter your country of residence: ")


# Appropraite Data Type
customer_id = str(customer_id)
customer_name = str(customer_name)
customer_age = int(customer_age)
monthly_income = float(monthly_income)
credit_score = int(credit_score)
number_of_missed_payments = int(number_of_missed_payments)
country_of_residence = str(country_of_residence)


# Organized Data
customer_info = {
    "customer_id": customer_id,
    "customer_name": customer_name,
    "customer_age": customer_age,
    "monthly_income": monthly_income,
    "credit_score": credit_score,
    "number_of_missed_payments": number_of_missed_payments,
    "country_of_residence": country_of_residence
}


# Restricted Country
restricted_countries = ["india", "pakistan", "isreal", "iraq"]


# Eligibility Rule
age_rule = customer_age > 21 and customer_age < 60
income_rule = monthly_income >= 150000
credit_rule = credit_score >= 700
payment_rule = number_of_missed_payments <= 2
country_rule = customer_info["country_of_residence"].lower() not in restricted_countries


# Eligibility Rule Result
if age_rule and income_rule and credit_rule and payment_rule and country_rule:
    print("Congratulations! You are eligible for a loan from SIGMA Bank")
else:
    print("Sorry, you are not eligible for a loan from SIGMA Bank")