# -*- coding: utf-8 -*-
"""A Smart Risk Alert System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWkYOqEkrIJEfyLmBL5IizScYtUHE4sg
"""

print("Hi there! Welcome to the proactive smart risk alert system where different risk categories are being analysed")

# Customer's Information
print("Please enter your information below:")
customer_id = str(input("Customer ID: "))
age = int(input("Age: "))
monthly_income = float(input("Monthly Income: "))
credit_score = int(input("Credit Score: "))
number_of_missed_payments = int(input("Number of Missed Payments: "))

# Risk Classification
if credit_score < 600 or number_of_missed_payments > 3:
  print("High Risk")
elif 600 <= credit_score <= 699 and number_of_missed_payments <= 2:
  print("Medium Risk")
elif credit_score >= 700 and (number_of_missed_payments == 0 or number_of_missed_payments == 1) and monthly_income >= 200000:
  print("Low Risk")
else:
  print("Medium Risk")