# -*- coding: utf-8 -*-
"""Capstone Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkNa9GOTEXgDYvqkSu5ofa-QAPDdyv8-
"""

"""
 Welcome Message
 Businesss Data Analyzer System
 """

 print("Welcome to Business Data Analyzer System.")
 print("A system that analyze retail product performance metrics without spreadsheets,")

# Business Dataset

products = ["Laptop","Phone","Tablet","Headphones"]
sales_data = {
    "Laptop":350000,
    "Phone":500000,
    "Tablet":150000,
    "Headphones":80000
    }
stock_levels = {
    "Laptop":5,
    "Phone":12,
    "Tablet":3,
    "Headphones":20
    }
sales_target = 200000
low_stock_threshold = 5

# Analysis Section
print("Product Analysis:")
for product in products:
  sales = str (sales_data[product])
  stock = str (stock_levels[product])
  print(f"Product: {product}, Sales: {sales}, Stock: {stock}")

# Sales Performance Check
print("Sales Performance and Stock Level Status:")
for product in products:
  sales = sales_data[product]
  stock = stock_levels[product]
  if sales > sales_target and stock > low_stock_threshold:
    print(f"{product}: Sales Performance: Target Met, Stock Level: In Stock")
  elif sales > sales_target and stock <= low_stock_threshold:
    print(f"{product}: Sales Performance: Target Met, Stock Level: Out of Stock")
  elif sales <= sales_target and stock > low_stock_threshold:
    print(f"{product}: Sales Performance: Target Not Met, Stock Level: In Stock")
  else:
    print(f"{product}: Sales Performance: Target Not Met, Stock Level: Out of Stock")

"""
Business Summary
Average Sales
"""
total_sales = sum(sales_data.values())
average_sales = total_sales / len(products)
print(f"Average Sales: {average_sales:.2f}")

"""
 Welcome Message
 Businesss Data Analyzer System
 """
 print("Welcome to Business Data Analyzer System.")
 print("A system that analyze retail product performance metrics without spreadsheets,")


 # Business Dataset

products = ["Laptop","Phone","Tablet","Headphones"]
sales_data = {
    "Laptop":350000,
    "Phone":500000,
    "Tablet":150000,
    "Headphones":80000
    }
stock_levels = {
    "Laptop":5,
    "Phone":12,
    "Tablet":3,
    "Headphones":20
    }
sales_target = 200000
low_stock_threshold = 5

# Analysis Section
print("Product Analysis:")
for product in products:
  sales = str (sales_data[product])
  stock = str (stock_levels[product])
  print(f"Product: {product}, Sales: {sales}, Stock: {stock}")

# Sales Performance Check
print("Sales Performance and Stock Level Status:")
for product in products:
  sales = sales_data[product]
  stock = stock_levels[product]
  if sales > sales_target and stock > low_stock_threshold:
    print(f"{product}: Sales Performance: Target Met, Stock Level: In Stock")
  elif sales > sales_target and stock <= low_stock_threshold:
    print(f"{product}: Sales Performance: Target Met, Stock Level: Out of Stock")
  elif sales <= sales_target and stock > low_stock_threshold:
    print(f"{product}: Sales Performance: Target Not Met, Stock Level: In Stock")
  else:
    print(f"{product}: Sales Performance: Target Not Met, Stock Level: Out of Stock")


"""
Business Summary
Average Sales
"""
total_sales = sum(sales_data.values())
average_sales = total_sales / len(products)
print(f"Average Sales: {average_sales:.2f}")