# -*- coding: utf-8 -*-
"""TuneTech Expense Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PLbciWyKRRWKA2dEDK0HqWZ6PmgKIDWe
"""

"""
TuneTech Expense Tracker
with basic Python
"""

# Greetings
print("Good day!!!")
print("Welcome to TuneTech Expense Tracker ")

# Allow User To Input Daily Budget
daily_budget = float(input("Please enter your daily budget: $"))
print(f"Your daily budget is: ${daily_budget:.2f}")

# Daily Expenses
marketing = float(input("Enter marketing expenses: $"))
development_tools = float(input("Enter development tool expenses: $"))
team_perks = float(input("Enter team perks expenses: $"))

# Total Daily Expenses
total_daily_expenses = marketing + development_tools + team_perks
print(f"Total daily expenses: ${total_daily_expenses:.2f}")

"""
Average Daily Expenses
Number of Daily Expenses
"""
num_daily_expenses = 3
average_daily_expenses = total_daily_expenses / num_daily_expenses

print(f"Your average daily expenses: ${average_daily_expenses:.2f}")

"""
Check For Overbudget
With Boolean Logic
"""
is_overbudget = total_daily_expenses > daily_budget
print(f"Is overbudget: {is_overbudget}")